// Generated by CoffeeScript 1.8.0
(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  this.MTwist = (function() {
    function MTwist(seed) {
      var mti, uint32mul, _i;
      if (seed == null) {
        seed = Math.random() * 4294967295;
      }
      this.randomIntBetween = __bind(this.randomIntBetween, this);
      this.randomIntBelow = __bind(this.randomIntBelow, this);
      this.random = __bind(this.random, this);
      this.randomUint32 = __bind(this.randomUint32, this);
      uint32mul = function(n1, n2) {
        var n1High16, n1Low16, n2High16, n2Low16;
        n1Low16 = n1 & 0x0000ffff;
        n1High16 = n1 >>> 16;
        n2Low16 = n2 & 0x0000ffff;
        n2High16 = n2 >>> 16;
        return ((((n1 & 0xffff0000) * n2) >>> 0) + (((n1 & 0x0000ffff) * n2) >>> 0)) >>> 0;
      };
      this.mt = new Array(624);
      this.mt[0] = seed >>> 0;
      for (mti = _i = 1; _i < 624; mti = ++_i) {
        this.mt[mti] = (uint32mul(1812433253, this.mt[mti - 1] ^ (this.mt[mti - 1] >>> 30)) + mti) >>> 0;
      }
      this.mti = mti;
    }

    MTwist.prototype.randomUint32 = function() {
      var i, y, _i, _j;
      if (this.mti >= 624) {
        for (i = _i = 0; _i < 227; i = ++_i) {
          y = ((this.mt[i] & 0x80000000) | (this.mt[i + 1] & 0x7fffffff)) >>> 0;
          this.mt[i] = (this.mt[i + 397] ^ (y >>> 1) ^ (y & 1 ? 0x9908b0df : 0)) >>> 0;
        }
        for (i = _j = 227; _j < 623; i = ++_j) {
          y = ((this.mt[i] & 0x80000000) | (this.mt[i + 1] & 0x7fffffff)) >>> 0;
          this.mt[i] = (this.mt[i - 227] ^ (y >>> 1) ^ (y & 1 ? 0x9908b0df : 0)) >>> 0;
        }
        y = ((this.mt[623] & 0x80000000) | (this.mt[0] & 0x7fffffff)) >>> 0;
        this.mt[623] = (this.mt[396] ^ (y >>> 1) ^ (y & 1 ? 0x9908b0df : 0)) >>> 0;
        this.mti = 0;
      }
      y = this.mt[this.mti++];
      y = (y ^ (y >>> 11)) >>> 0;
      y = (y ^ ((y << 7) & 0x9d2c5680)) >>> 0;
      y = (y ^ ((y << 15) & 0xefc60000)) >>> 0;
      y = (y ^ (y >>> 18)) >>> 0;
      return y;
    };

    MTwist.prototype.random = function() {
      return this.randomUint32() / 4294967296;
    };

    MTwist.prototype.randomIntBelow = function(maxPlusOne) {
      var bitMask, bitsNeeded, int;
      if (maxPlusOne < 1) {
        throw "Upper bound must be greater than or equal to 1";
      }
      if (maxPlusOne === 1) {
        return 0;
      }
      bitsNeeded = (maxPlusOne - 1).toString(2).length;
      bitMask = (1 << bitsNeeded) - 1;
      while (true) {
        int = this.randomUint32() & bitMask;
        if (int < maxPlusOne) {
          return int;
        }
      }
    };

    MTwist.prototype.randomIntBetween = function(inclusiveMin, inclusiveMax) {
      return inclusiveMin + this.randomIntBelow(inclusiveMax - inclusiveMin + 1);
    };

    MTwist.test = function() {
      var i, iterationFactor, iterations, j, mtwist, seed, _i, _j;
      seed = 1234567890;
      iterationFactor = 10000;
      for (i = _i = 0; _i < 1000; i = ++_i) {
        mtwist = new MTwist(seed);
        iterations = Math.floor(mtwist.randomUint32() / iterationFactor);
        for (j = _j = 0; 0 <= iterations ? _j < iterations : _j > iterations; j = 0 <= iterations ? ++_j : --_j) {
          mtwist.randomUint32();
        }
        seed = mtwist.randomUint32();
      }
      return seed === 1240212512;
    };

    return MTwist;

  })();

}).call(this);
